#!/usr/bin/python3
# SPDX -FileCopyrightText:2022 Hayato Aizawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += float(line)
    except:
        ans += int(line)

print(ans)
if ans % 2 == 1:
        print('奇数')
else:
        print('偶数')


